### ISSUE TITLE
Make installation / compilation work on Windows

### ISSUE THREAD

**Issue by asieira** [asieira/SnakeCharmR#13]
Someone that has a working Windows box with R, a functioning C++ compiler that R can use, Python (including development libs and header files) should try to install SnakeCharmR and let me know how it goes.

![halp](http://i77.photobucket.com/albums/j65/beckyeckyecky/halp1.jpg)

**Comment by KhaoticMind** [comment]
For the time being the install on Windows is failing with the following message:

```
> install('c:/Users/ur57/Downloads/SnakeCharmR-master')
Installing SnakeCharmR
"C:/Users/ur57/Documents/R/R-3.2.2/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "c:/Users/ur57/Downloads/SnakeCharmR-master"  \
  --library="C:/Users/ur57/Documents/R/R-3.2.2/library" --install-tests 

ERROR:  Unix-only package
* removing 'C:/Users/ur57/Documents/R/R-3.2.2/library/SnakeCharmR'
Erro: Command failed (1)
> 
```

My config:

```
> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Portuguese_Brazil.1252  LC_CTYPE=Portuguese_Brazil.1252    LC_MONETARY=Portuguese_Brazil.1252 LC_NUMERIC=C                      
[5] LC_TIME=Portuguese_Brazil.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.11.1

loaded via a namespace (and not attached):
[1] tools_3.2.2   withr_1.0.1   memoise_1.0.0 digest_0.6.9 
```

**Comment by asieira** [comment]
Yeah, it's as I feared. I'll be forced to install Windows to get this done. 😱 

Thank you! 🙇

**Comment by casras111** [comment]
I see this issue is from May, checking, is there support for Windows in the CRAN or github version of this package?

thanks

**Comment by asieira** [comment]
No, not yet. I don't use R on Windows, so haven't gotten around to doing it. Any chance you could help out?

**Comment by mchlltt** [comment]
I may be able to help out on testing this (though I'm working on a work laptop without admin privileges, so TBD...). First, though, I had a quick question: are the instructions for Windows installation on [https://github.com/cjgb/rPython-win](https://github.com/cjgb/rPython-win) still useful? I found that because it was in the INSTALL file, which is still in the most recent SnakeCharmR release. As far as I can find, there aren't any current Windows installation instructions/suggestions.

**Comment by asieira** [comment]
Thank you, that would be awesome!

The documentation reference is no longer valid. I still need to update the documentation and remove any left over references to rPython.

**Comment by mchlltt** [comment]
Got it :) Do you have any suggestions for how I go about attempting installation?

**Comment by asieira** [comment]
I would start by looking at https://stevemosher.wordpress.com/ten-steps-to-building-an-r-package-under-windows/ for how to set up the system correctly. But at this point what needs to be done is less test the package (I already know it doesn't work) to actually making it compile and run properly.

**Comment by mchlltt** [comment]
Ah, OK. Unfortunately, I think that's over my head/skill level, but I'll keep subscribed to this issue in case there's somewhere I can jump in later on.

**Comment by mattfidler** [comment]
I got it to run in my system with only minimal changes.

**Comment by asieira** [comment]
Really? Those are great news! I'd love to hear what those changes were, @mattfidler. 

Can you either share what worked for you or, better yet, submit a pull request?

**Comment by mattfidler** [comment]
See #37

**Comment by mattfidler** [comment]
Like rPython, I had to use python 2.7 installed in the default location, but everything checked out OK.
