### ISSUE TITLE
Better handling of unicode in rcpp_Py_get_var

### ISSUE THREAD

**Issue by asieira** [asieira/SnakeCharmR#20]
Current code assumes whether return value of `json.dumps` will be `string`/`bytes` or `unicode` according to Python version, and also assumes native encoding is UTF-8. Not good.

**Comment by hrbrmstr** [comment]
take a look at how `jsonlite` handles this. i think it'll be drop-in-able

**Comment by asieira** [comment]
@hrbrmstr actually it was more an impedance mismatch between R, Rcpp and Python C API thing. Everything was working ok if the native system encoding was UTF-8, but now it should work even if that's  not the case.
