### ISSUE TITLE
put this on CRAN?

### ISSUE THREAD

**Issue by flying-sheep** [asieira/SnakeCharmR#22]
i’d like to see this on CRAN so that i can use it as a dependency :smile:

**Comment by asieira** [comment]
I agree, but I haven't had the time to make sure this works in Windows as well, which I think would be a requirement for submitting. Any chance you could help with that?

See https://github.com/asieira/SnakeCharmR/issues/13 for more info.

**Comment by asieira** [comment]
In the meantime, you might want to take a look at https://github.com/hadley/devtools/pull/902 and https://github.com/hadley/devtools/blob/master/vignettes/dependencies.Rmd for guidance on how to use GitHub-based packages as dependencies to your own package.

**Comment by asieira** [comment]
Hmmm... so actually reading the [CRAN policies](https://cran.r-project.org/web/packages/policies.html) it appears that supporting two major R platforms is enough to have a package accepted!

So I have just submitted SnakeCharmR 1.0.4 to CRAN. Fingers crossed as to what they think of it. 🙏

**Comment by asieira** [comment]
There you go: https://cran.r-project.org/web/packages/SnakeCharmR/index.html
