### ISSUE TITLE
dynamically use python 2 or 3

### ISSUE THREAD

**Issue by flying-sheep** [asieira/SnakeCharmR#23]
a global selection of python 2 or 3 isn’t very useful.

an adequate solution would be to link to python2 and python3 at compile time and provide a runtime selection method of which to use

**Comment by hrbrmstr** [comment]
sweet! PR?

**Comment by asieira** [comment]
Don't think this is technically feasible, will close this for now. If someone submits a PR for this I'll reopen this.
