### ISSUE TITLE
Python 3 linking problem

### ISSUE THREAD

**Issue by lfdmotta** [asieira/SnakeCharmR#33]
Hi,

I tried the following to install SnakeCharmR set to use Python 3:
`
install.packages("SnakeCharmR", configure.vars = "SNAKECHARMR_PYTHON_VERSION=3.5")`

This gives the following error:

> python.cpp:50:19: error: use of undeclared identifier 'PyString_AS_STRING'
>     String retval(PyString_AS_STRING(PyUnicode_AsUTF8String(value)), CE_UTF8);
>                   ^
> python.cpp:56:14: error: use of undeclared identifier 'PyString_Check'; did you mean 'PyMapping_Check'?
>   } else if (PyString_Check(value))
>              ^~~~~~~~~~~~~~
>              PyMapping_Check
> /Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m/abstract.h:1152:22: note: 'PyMapping_Check' declared here
>      PyAPI_FUNC(int) PyMapping_Check(PyObject *o);
>                      ^
> python.cpp:57:19: error: use of undeclared identifier 'PyString_AS_STRING'
>     return String(PyString_AS_STRING(value));
>                   ^
> 3 errors generated.

Apparently PyString_ are no longer available in Python 3 API:

https://docs.python.org/3/howto/cporting.html?highlight=pystring

Perhaps pyBytes_Check should be used instead?

**Comment by asieira** [comment]
Funny that the documentation mentions this, but that does not seem to work:
```
Python 2.6 and later provide a compatibility header, bytesobject.h, mapping PyBytes names to PyString ones.
```

I have been able to replicate the problem and will attempt a fix shortly. Thank you for reporting this.

**Comment by asieira** [comment]
I have merged the fix to master, you can use devtools::install_github to install directly from here and confirm that this has worked.

**Comment by asieira** [comment]
Just wanted to let you know SnakeCharmR 1.0.6 is on CRAN now, and it fixes this problem. Thanks again for reporting this. 🙇
