### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by UNCcrawler** [asieira/SnakeCharmR#45]
Hi, I am a R user and have no knowledge in python. One R package RxODE suggests to install SnakeCharmR to integrate python and R in order to activate a function. However, I got the following error message. Could you please tell me how to fix it? 

Hi, I am a R user and have no knowledge in python. One R package RxODE suggests to install SnakeCharmR to integrate python and R in order to activate a function. However, I got the following error message. Could you please tell me how to fix it? Is it necessary to define PYTHONHOME as suggested and how? Thank you!

* installing *source* package 'SnakeCharmR' ...
Found Python version 2.7
Detected EXEC_PREFIX=C:\Users\xxx\AppData\Local\Continuum\anaconda2
PYTHONHOME is not defined, this might cause an error when loading the package.
Please try setting it to C:\Users\xxx\AppData\Local\Continuum\anaconda2 on a system level if you have issues.
Detected library dir C:\Users\xxx\AppData\Local\Continuum\anaconda2/libs
Detected library name python27
Detected include dir C:\Users\xxx\AppData\Local\Continuum\anaconda2/include
--------[[begin src/Makevars.win]]--------
PKG_LIBS=-L'C:\Users\xxx\AppData\Local\Continuum\anaconda2/libs' -lpython27
PKG_CPPFLAGS=-I'C:\Users\xxx\AppData\Local\Continuum\anaconda2/include'
CXX_STD=CXX11
--------[[end src/Makevars.win]]--------
** libs
Warning: this package has a non-empty 'configure.win' file,
so building only the main architecture

C:/RBuildTools/3.4/mingw_64/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I'C:\Users\xxx\AppData\Local\Continuum\anaconda2/include'   -I"C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c RcppExports.cpp -o RcppExports.o
C:/RBuildTools/3.4/mingw_64/bin/g++  -std=c++0x -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I'C:\Users\xxx\AppData\Local\Continuum\anaconda2/include'   -I"C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include" -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -mtune=core2 -c python.cpp -o python.o
In file included from C:\Users\xxx\AppData\Local\Continuum\anaconda2/include/Python.h:8:0,
                 from python.cpp:4:
C:\Users\xxx\AppData\Local\Continuum\anaconda2/include/pyconfig.h:71:0: warning: "HAVE_HYPOT" redefined
 #define HAVE_HYPOT
 ^
In file included from C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include/RcppCommon.h:81:0,
                 from C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
C:/PROGRA~1/R/R-33~1.3/include/Rmath.h:64:0: note: this is the location of the previous definition
 # define HAVE_HYPOT 1
 ^
In file included from C:\Users\xxx\AppData\Local\Continuum\anaconda2/include/Python.h:8:0,
                 from python.cpp:4:
C:\Users\xxx\AppData\Local\Continuum\anaconda2/include/pyconfig.h:370:0: warning: "SIZEOF_SIZE_T" redefined
 # define SIZEOF_SIZE_T 4
 ^
In file included from C:/PROGRA~1/R/R-33~1.3/include/R.h:74:0,
                 from C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include/Rcpp/r/headers.h:52,
                 from C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include/RcppCommon.h:38,
                 from C:/Users/xxx/Documents/R/win-library/3.3/Rcpp/include/Rcpp.h:27,
                 from python.cpp:1:
C:/PROGRA~1/R/R-33~1.3/include/Rconfig.h:21:0: note: this is the location of the previous definition
 #define SIZEOF_SIZE_T 8
 ^
C:/RBuildTools/3.4/mingw_64/bin/g++ -shared -s -static-libgcc -o SnakeCharmR.dll tmp.def RcppExports.o python.o -LC:\Users\xxx\AppData\Local\Continuum\anaconda2/libs -lpython27 -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-33~1.3/bin/x64 -lR
installing to C:/Users/xxx/Documents/R/win-library/3.3/SnakeCharmR/libs/x64
** R
** inst
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
ERROR: loading failed
* removing 'C:/Users/xxx/Documents/R/win-library/3.3/SnakeCharmR'
Installation failed: Command failed (1)

**Comment by billchenxi** [comment]
Do this: `install_github("asieira/SnakeCharmR", INSTALL_opts="--no-multiarch")`
